//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorGasAPI.Repositorio.Resources.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SensorGasAPI.Repositorio.Resources.Scripts.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   SELECT Consulta.DataRealizacaoConsulta DataRealizacaoConsulta
        ///       , (SELECT COUNT(SituacaoConsulta) FROM Consulta C1 
        ///           WHERE Consulta.CodigoProfissional = C1.CodigoProfissional
        ///             AND DATE(Consulta.DataRealizacaoConsulta) = DATE(C1.DataRealizacaoConsulta)
        ///             AND SituacaoConsulta = 0) QuantidadeConsultasAbertas /* Quantidade de Consultas Abertas */
        ///       , (SELECT COUNT(SituacaoConsulta) FROM Consulta C1 
        ///           WHERE Consulta.CodigoProfissional = C1.CodigoProfis [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BuscarSituacaoDatasDoMes {
            get {
                return ResourceManager.GetString("BuscarSituacaoDatasDoMes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO ConfiguracaoConsulta 
        ///          ( CodigoProfissional
        ///          , PrecoConsultaProfissional
        ///          , IntervaloConsultaProfissional ) 
        ///     VALUES
        ///          ( @CodigoProfissional
        ///          , @PrecoConsultaProfissional
        ///          , @IntervaloConsultaProfissional )
        ///.
        /// </summary>
        internal static string CargaConfiguracaoConsulta {
            get {
                return ResourceManager.GetString("CargaConfiguracaoConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO ConfiguracaoHorario 
        ///          ( CodigoProfissional
        ///          , CodigoDiaConsulta
        ///          , AtivacaoConfiguracaoHorario
        ///          , HoraInicialConfiguracaoHorario
        ///          , MinutoInicialConfiguracaoHorario
        ///          , HoraFinalConfiguracaoHorario
        ///          , MinutoFinalConfiguracaoHorario) 
        ///     VALUES
        ///          ( @CodigoProfissional
        ///          , @CodigoDiaConsulta
        ///          , @AtivacaoConfiguracaoHorario
        ///          , @HoraInicialConfiguracaoHorario
        ///          , @MinutoInicialConfi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CargaConfiguracaoHorario {
            get {
                return ResourceManager.GetString("CargaConfiguracaoHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Consulta
        ///          ( CodigoProfissional
        ///          , CodigoPaciente
        ///          , SituacaoConsulta
        ///          , TipoPagamentoConsulta
        ///          , DataRealizacaoConsulta
        ///          , HoraInicialConsulta
        ///          , MinutoInicialConsulta
        ///          , HoraFinalConsulta
        ///          , MinutoFinalConsulta )
        ///   VALUES ( @CodigoProfissional
        ///          , @CodigoPaciente
        ///          , @SituacaoConsulta
        ///          , @TipoPagamentoConsulta
        ///          , @DataRealizacaoConsulta
        ///          , @HoraInicialConsu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CargaConsulta {
            get {
                return ResourceManager.GetString("CargaConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Estado (DescricaoEstado, AbreviacaoEstado) 
        ///     VALUES
        ///           (&apos;Acre&apos;, &apos;AC&apos;),
        ///           (&apos;Alagoas&apos;, &apos;AL&apos;),
        ///           (&apos;Amazonas&apos;, &apos;AM&apos;),
        ///           (&apos;Amapá&apos;, &apos;AP&apos;),
        ///           (&apos;Bahia&apos;, &apos;BA&apos;),
        ///           (&apos;Ceará&apos;, &apos;CE&apos;),
        ///           (&apos;Distrito Federal&apos;, &apos;DF&apos;),
        ///           (&apos;Espírito Santo&apos;, &apos;ES&apos;),
        ///           (&apos;Goiás&apos;, &apos;GO&apos;),
        ///           (&apos;Maranhão&apos;, &apos;MA&apos;),
        ///           (&apos;Minas Gerais&apos;, &apos;MG&apos;),
        ///           (&apos;Mato Grosso do Sul&apos;, &apos;MS&apos;),
        ///           (&apos;Mato Grosso&apos;, &apos;MT&apos;),
        ///           ( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CargaEstado {
            get {
                return ResourceManager.GetString("CargaEstado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Municipio(DescricaoMunicipio, CodigoEstado) 
        ///     VALUES
        ///           (&apos;Brasiléia&apos;, 1),
        ///           (&apos;Bujari&apos;, 1),
        ///           (&apos;Capixaba&apos;, 1),
        ///           (&apos;Cruzeiro do Sul&apos;, 1),
        ///           (&apos;Epitaciolândia&apos;, 1),
        ///           (&apos;Feijó&apos;, 1),
        ///           (&apos;Jordão&apos;, 1),
        ///           (&apos;Mancio Lima&apos;, 1),
        ///           (&apos;Manoel Urbano&apos;, 1),
        ///           (&apos;Marechal Thaumaturgo&apos;, 1),
        ///           (&apos;Plácido de Castro&apos;, 1),
        ///           (&apos;Porto Acre&apos;, 1),
        ///           (&apos;Porto Walter&apos;, 1),
        ///           (&apos;Rio Branc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CargaMunicipio {
            get {
                return ResourceManager.GetString("CargaMunicipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///  FROM UsuarioGlobal.
        /// </summary>
        internal static string CheckUsuarioGlobal {
            get {
                return ResourceManager.GetString("CheckUsuarioGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       SELECT COALESCE((SELECT SUM(COALESCE(A1.NotaAvaliacao, 0))
        ///                         FROM Avaliacao A1
        ///                        WHERE 1 = 1
        ///                          AND A1.CodigoAvaliacao = Avaliacao.CodigoAvaliacao) /
        ///                      (SELECT COUNT(Avaliacao.CodigoAvaliacao)
        ///                         FROM Avaliacao A1
        ///                        WHERE 1 = 1
        ///                          AND A1.CodigoAvaliacao = Avaliacao.CodigoAvaliacao
        ///                          AND A1.CodigoAvaliacao IS NOT NULL) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassificacaoProfissional {
            get {
                return ResourceManager.GetString("ClassificacaoProfissional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  INSERT INTO ConfiguracaoHorario
        ///           ( CodigoProfissional
        ///           , CodigoDiaConsulta )
        ///      VALUES 
        ///           ( @CodigoProfissional, 1 ),
        ///           ( @CodigoProfissional, 2 ),
        ///           ( @CodigoProfissional, 3 ),
        ///           ( @CodigoProfissional, 4 ),
        ///           ( @CodigoProfissional, 5 ),
        ///           ( @CodigoProfissional, 6 ),
        ///           ( @CodigoProfissional, 7 ); .
        /// </summary>
        internal static string ConfiguracaoHorarioInsert {
            get {
                return ResourceManager.GetString("ConfiguracaoHorarioInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  UPDATE ConfiguracaoHorario
        ///    SET AtivacaoConfiguracaoHorario = @AtivacaoConfiguracaoHorario
        ///      , HoraInicialConfiguracaoHorario = @HoraInicialConfiguracaoHorario
        ///      , MinutoInicialConfiguracaoHorario = @MinutoInicialConfiguracaoHorario
        ///      , HoraFinalConfiguracaoHorario = @HoraFinalConfiguracaoHorario
        ///      , MinutoFinalConfiguracaoHorario = @MinutoFinalConfiguracaoHorario
        ///  WHERE 1 = 1
        ///    AND CodigoProfissional = @CodigoProfissional
        ///    AND CodigoDiaConsulta = @CodigoDiaConsulta.
        /// </summary>
        internal static string ConfiguracaoHorarioUpdate {
            get {
                return ResourceManager.GetString("ConfiguracaoHorarioUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Consulta
        ///          ( CodigoProfissional
        ///          , CodigoPaciente
        ///          , SituacaoConsulta
        ///          , TipoPagamentoConsulta
        ///          , DataRealizacaoConsulta
        ///          , HoraInicialConsulta 
        ///          , MinutoInicialConsulta
        ///          , HoraFinalConsulta
        ///          , MinutoFinalConsulta )
        ///    VALUES
        ///          ( @CodigoProfissional
        ///          , @CodigoPaciente
        ///          , @SituacaoConsulta
        ///          , @TipoPagamentoConsulta
        ///          , @DataRealizacaoConsulta
        ///          , @Hor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConsultaInsert {
            get {
                return ResourceManager.GetString("ConsultaInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Consulta
        ///   SET CodigoProfissional = @CodigoProfissional
        ///     , CodigoPaciente = @CodigoPaciente
        ///     , SituacaoConsulta = @SituacaoConsulta
        ///     , TipoPagamentoConsulta = @TipoPagamentoConsulta
        ///     , DataRealizacaoConsulta = @DataRealizacaoConsulta
        ///     , HoraInicialConsulta = @HoraInicialConsulta 
        ///     , MinutoInicialConsulta = @MinutoInicialConsulta
        ///     , HoraFinalConsulta = @HoraFinalConsulta
        ///     , MinutoFinalConsulta = @MinutoFinalConsulta
        /// WHERE 1 = 1
        ///   AND CodigoConsulta = @Codi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConsultaUpdate {
            get {
                return ResourceManager.GetString("ConsultaUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  INSERT INTO ConfiguracaoConsulta
        ///           ( CodigoProfissional
        ///           , PrecoConsultaProfissional
        ///           , IntervaloConsultaProfissional )
        ///      VALUES 
        ///           ( @CodigoProfissional
        ///           , @PrecoConsultaProfissional
        ///           , @IntervaloConsultaProfissional ).
        /// </summary>
        internal static string DadosConsultaInsert {
            get {
                return ResourceManager.GetString("DadosConsultaInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  UPDATE ConfiguracaoConsulta
        ///    SET PrecoConsultaProfissional = @PrecoConsultaProfissional
        ///      , IntervaloConsultaProfissional = @IntervaloConsultaProfissional
        ///  WHERE 1 = 1
        ///    AND CodigoProfissional = @CodigoProfissional.
        /// </summary>
        internal static string DadosConsultaUpdate {
            get {
                return ResourceManager.GetString("DadosConsultaUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        SELECT Consulta.CodigoConsulta CodigoConsulta
        ///           ,  Consulta.DataRealizacaoConsulta
        ///           , (Pessoa.PrimeiroNomePessoa || &apos; &apos; || Pessoa.SobreNomePessoa) NomeProfissional
        ///           ,  Avaliacao.CodigoAvaliacao CodigoAvaliacao
        ///           ,  Avaliacao.SituacaoAvaliacao
        ///           ,  Avaliacao.NotaAvaliacao
        ///           ,  Avaliacao.DescricaoAvaliacao
        ///         FROM Consulta
        ///   INNER JOIN Profissional ON Consulta.CodigoProfissional = Profissional.CodigoProfissional
        ///   INNER JOIN Usuar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DetalheAvaliacaoPaciente {
            get {
                return ResourceManager.GetString("DetalheAvaliacaoPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      SELECT (Pessoa.PrimeiroNomePessoa || &apos; &apos; || Pessoa.SobreNomePessoa) NomeSolicitante
        ///           , Consulta.CodigoConsulta CodigoConsulta
        ///           , Consulta.CodigoProfissional
        ///           , Consulta.CodigoPaciente
        ///           , Consulta.DataRealizacaoConsulta
        ///           , CAST(Consulta.HoraInicialConsulta AS VARCHAR (2)) HoraInicio
        ///           , CAST(Consulta.MinutoInicialConsulta AS VARCHAR) MinutoInicio
        ///           , CAST(Consulta.HoraFinalConsulta AS VARCHAR) HoraFim
        ///           , CAST(Consulta. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DetalheGerenciarConsultas {
            get {
                return ResourceManager.GetString("DetalheGerenciarConsultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      SELECT (Pessoa.PrimeiroNomePessoa || &apos; &apos; || Pessoa.SobreNomePessoa) NomeProfissional
        ///           , Consulta.CodigoConsulta CodigoConsulta
        ///           , Consulta.CodigoProfissional
        ///           , Consulta.CodigoPaciente
        ///           , Consulta.DataRealizacaoConsulta
        ///           , CAST(Consulta.HoraInicialConsulta AS VARCHAR (2)) HoraInicio
        ///           , CAST(Consulta.MinutoInicialConsulta AS VARCHAR) MinutoInicio
        ///           , CAST(Consulta.HoraFinalConsulta AS VARCHAR) HoraFim
        ///           , CAST(Consulta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DetalheMinhaConsulta {
            get {
                return ResourceManager.GetString("DetalheMinhaConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DISTINCT Imagens.Imagem Imagem
        ///              , Profissional.CodigoProfissional CodigoProfissional
        ///              , (Pessoa.PrimeiroNomePessoa || &apos; &apos; || Pessoa.SobreNomePessoa) NomeProfissional 
        ///              , (ClasseProfissional.ConselhoProfissional || &apos; &apos; || CAST(RelacaoProfissionalClasse.NumeroRegistroProfissional AS VARCHAR) || &apos;-&apos; ||  Estado.AbreviacaoEstado) RegistroProfissional 
        ///              , EspecialidadeProfissional.DescricaoEspecialidadeProfissional EspecialidadeProfissional 
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DetalheProfissional {
            get {
                return ResourceManager.GetString("DetalheProfissional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        SELECT Consulta.CodigoConsulta CodigoConsulta
        ///           ,  Consulta.DataRealizacaoConsulta
        ///           , (Pessoa.PrimeiroNomePessoa || &apos; &apos; || Pessoa.SobreNomePessoa) NomePaciente
        ///           ,  Avaliacao.CodigoAvaliacao CodigoAvaliacao
        ///           ,  Avaliacao.SituacaoAvaliacao
        ///           ,  Avaliacao.NotaAvaliacao
        ///           ,  Avaliacao.DescricaoAvaliacao
        ///         FROM Consulta
        ///   INNER JOIN Paciente ON Consulta.CodigoPaciente = Paciente.CodigoPaciente
        ///   INNER JOIN Usuario ON Paciente.Codig [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DetalheReputacao {
            get {
                return ResourceManager.GetString("DetalheReputacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      SELECT (Pessoa.PrimeiroNomePessoa || &apos; &apos; || Pessoa.SobreNomePessoa) NomeProfissional
        ///           , Consulta.CodigoConsulta
        ///           , Consulta.CodigoProfissional
        ///           , Consulta.CodigoPaciente
        ///           , Consulta.DataRealizacaoConsulta
        ///           , Consulta.SituacaoConsulta
        ///           , Tratamento.CodigoTratamento
        ///           , Tratamento.NomeTratamento
        ///           , Tratamento.DescricaoTratamento
        ///           , Tratamento.InicioTratamento
        ///           , Tratamento.TerminoTratamento
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DetalheTratamento {
            get {
                return ResourceManager.GetString("DetalheTratamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CheckEmail
        ///     VALUES (@CodigoConsulta).
        /// </summary>
        internal static string InserirCheckEmail {
            get {
                return ResourceManager.GetString("InserirCheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  INSERT INTO UsuarioGlobal
        ///           ( CodigoUsuario
        ///           , CodigoPaciente
        ///           , TipoUsuario
        ///           , LoginUsuario
        ///           , SenhaUsuario
        ///           , NomeUsuario
        ///           , EmailUsuario )
        ///     VALUES 
        ///           ( @CodigoUsuario
        ///           , @CodigoPaciente
        ///           , @TipoUsuario
        ///           , @LoginUsuario
        ///           , @SenhaUsuario
        ///           , @NomeUsuario
        ///           , @EmailUsuario ).
        /// </summary>
        internal static string InserirUsuarioGlobal {
            get {
                return ResourceManager.GetString("InserirUsuarioGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* INÍCIO */
        ///
        ///   /* Insert da tabela &quot;Pessoa&quot; */
        ///   INSERT INTO Pessoa
        ///        ( PrimeiroNomePessoa
        ///        , SobreNomePessoa
        ///        , CPFPessoa
        ///        , DataNascimentoPessoa )
        ///   VALUES
        ///        ( @PrimeiroNomePessoa
        ///        , @SobreNomePessoa
        ///        , @CPFPessoa
        ///        , @DataNascimentoPessoa );
        ///   
        ///   /* Insert tabela &quot;Usuario&quot; */
        ///   INSERT INTO Usuario
        ///        ( CodigoPessoa
        ///        , LoginUsuario
        ///        , SenhaUsuario
        ///        , TipoUsuario )
        ///   VALUES
        ///        ( (SELECT CodigoPe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertCadastroProfissional {
            get {
                return ResourceManager.GetString("InsertCadastroProfissional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    INSERT INTO Pessoa 
        ///        ( PrimeiroNomePessoa 
        ///        , SobreNomePessoa 
        ///        , CPFPessoa 
        ///        , DataNascimentoPessoa ) 
        ///   VALUES 
        ///        ( @primeiroNome 
        ///        , @sobreNome
        ///        , @cpfPessoa
        ///        , @dataNascimento ); 
        ///
        ///   INSERT INTO Usuario 
        ///        ( CodigoPessoa 
        ///        , LoginUsuario 
        ///        , SenhaUsuario 
        ///        , TipoUsuario ) 
        ///   VALUES 
        ///        ( (SELECT CodigoPessoa FROM Pessoa WHERE CPFPessoa = @cpfPessoa) 
        ///        , @login
        ///        , @senha
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertCadastroUsuario {
            get {
                return ResourceManager.GetString("InsertCadastroUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO DiaConsulta 
        ///          ( CodigoDiaConsulta
        ///          , DescricaoDiaConsulta)
        ///     VALUES 
        ///          ( 1, &apos;Domingo&apos;),
        ///          ( 2, &apos;Segunda-Feira&apos;),
        ///          ( 3, &apos;Terça-Feira&apos;),
        ///          ( 4, &apos;Quarta-Feira&apos;),
        ///          ( 5, &apos;Quinta-Feira&apos;),
        ///          ( 6, &apos;Sexta-Feira&apos;),
        ///          ( 7, &apos;Sábado&apos;);.
        /// </summary>
        internal static string InsertDiaConsulta {
            get {
                return ResourceManager.GetString("InsertDiaConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Tratamento      
        ///          ( CodigoConsulta
        ///          , NomeTratamento
        ///          , DescricaoTratamento
        ///          , InicioTratamento
        ///          , TerminoTratamento
        ///          , HoraInicio
        ///          , MinutoInicio
        ///          , FrequenciaDias
        ///          , FrequenciaHoras
        ///          , TratamentoAtivado )
        ///     VALUES 
        ///          ( @CodigoConsulta
        ///          , @NomeTratamento
        ///          , @DescricaoTratamento
        ///          , @InicioTratamento
        ///          , @TerminoTratamento
        ///          , @HoraInicio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InsertTratamento {
            get {
                return ResourceManager.GetString("InsertTratamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      SELECT  Imagens.Imagem Imagem
        ///           , (Pessoa.PrimeiroNomePessoa || &apos; &apos; || Pessoa.SobreNomePessoa) NomeProfissional
        ///           , Consulta.CodigoConsulta CodigoConsulta
        ///           , Consulta.DataRealizacaoConsulta
        ///        FROM Consulta
        ///  INNER JOIN Profissional ON Consulta.CodigoProfissional = Profissional.CodigoProfissional
        ///  INNER JOIN Usuario ON Profissional.CodigoUsuario = Usuario.CodigoUsuario
        ///  INNER JOIN Pessoa ON Usuario.CodigoPessoa = Pessoa.CodigoPessoa
        ///   LEFT JOIN Imagens ON Usu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListaAvaliacoesPaciente {
            get {
                return ResourceManager.GetString("ListaAvaliacoesPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      SELECT  Consulta.CodigoConsulta
        ///        FROM Consulta
        ///       WHERE 1 = 1
        ///         AND Consulta.SituacaoConsulta = 4 /* 4 - Consulta Realizada */
        ///         AND Consulta.CodigoPaciente = @CodigoPaciente
        ///         AND Consulta.CodigoProfissional = @CodigoProfissional.
        /// </summary>
        internal static string ListaConsultasCargaAvaliacao {
            get {
                return ResourceManager.GetString("ListaConsultasCargaAvaliacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      SELECT * 
        ///       FROM ConfiguracaoHorario
        ///       JOIN DiaConsulta
        ///         ON DiaConsulta.CodigoDiaConsulta = ConfiguracaoHorario.CodigoDiaConsulta
        ///      WHERE 1 = 1
        ///        AND (CodigoProfissional = @CodigoProfissional).
        /// </summary>
        internal static string ListaDadosConfiguracaoHorario {
            get {
                return ResourceManager.GetString("ListaDadosConfiguracaoHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      SELECT (Pessoa.PrimeiroNomePessoa || &apos; &apos; || Pessoa.SobreNomePessoa) NomeProfissional
        ///           , Consulta.DataRealizacaoConsulta
        ///           , Consulta.CodigoConsulta
        ///        FROM Consulta
        ///  INNER JOIN Profissional ON Consulta.CodigoProfissional = Profissional.CodigoProfissional
        ///  INNER JOIN Usuario ON Profissional.CodigoUsuario = Usuario.CodigoUsuario
        ///  INNER JOIN Pessoa ON Usuario.CodigoPessoa = Pessoa.CodigoPessoa
        ///   LEFT JOIN Tratamento
        ///          ON Consulta.CodigoConsulta = Tratamento.Codi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListaDefinirTratamento {
            get {
                return ResourceManager.GetString("ListaDefinirTratamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///  FROM Estado.
        /// </summary>
        internal static string ListaEstados {
            get {
                return ResourceManager.GetString("ListaEstados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      SELECT  Imagens.Imagem Imagem
        ///           , (Pessoa.PrimeiroNomePessoa || &apos; &apos; || Pessoa.SobreNomePessoa) NomeSolicitante
        ///           , Consulta.CodigoConsulta CodigoConsulta
        ///           , Consulta.DataRealizacaoConsulta
        ///           , Consulta.SituacaoConsulta
        ///        FROM Consulta
        ///  INNER JOIN Paciente ON Consulta.CodigoPaciente = Paciente.CodigoPaciente
        ///  INNER JOIN Usuario ON Paciente.CodigoUsuario = Usuario.CodigoUsuario
        ///  INNER JOIN Pessoa ON Usuario.CodigoPessoa = Pessoa.CodigoPessoa
        ///   LEFT  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListaGerenciarConsultas {
            get {
                return ResourceManager.GetString("ListaGerenciarConsultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      SELECT  Imagens.Imagem Imagem
        ///           , (Pessoa.PrimeiroNomePessoa || &apos; &apos; || Pessoa.SobreNomePessoa) NomeProfissional
        ///           , Consulta.CodigoConsulta CodigoConsulta
        ///           , Consulta.DataRealizacaoConsulta
        ///        FROM Consulta
        ///  INNER JOIN Profissional ON Consulta.CodigoProfissional = Profissional.CodigoProfissional
        ///  INNER JOIN Usuario ON Profissional.CodigoUsuario = Usuario.CodigoUsuario
        ///  INNER JOIN Pessoa ON Usuario.CodigoPessoa = Pessoa.CodigoPessoa
        ///   LEFT JOIN Imagens ON Usu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListaMinhasConsultas {
            get {
                return ResourceManager.GetString("ListaMinhasConsultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///  FROM Municipio
        /// WHERE 1 = 1
        ///   AND CodigoEstado = @CodigoEstado.
        /// </summary>
        internal static string ListaMunicipios {
            get {
                return ResourceManager.GetString("ListaMunicipios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      SELECT  Imagens.Imagem Imagem
        ///           , (Pessoa.PrimeiroNomePessoa || &apos; &apos; || Pessoa.SobreNomePessoa) NomePaciente
        ///           , Consulta.CodigoConsulta CodigoConsulta
        ///           , Consulta.DataRealizacaoConsulta
        ///           , Avaliacao.NotaAvaliacao NotaAvaliacao
        ///        FROM Consulta
        ///  INNER JOIN Paciente ON Consulta.CodigoPaciente = Paciente.CodigoPaciente
        ///  INNER JOIN Usuario ON Paciente.CodigoUsuario = Usuario.CodigoUsuario
        ///  INNER JOIN Pessoa ON Usuario.CodigoPessoa = Pessoa.CodigoPessoa
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListaReputacao {
            get {
                return ResourceManager.GetString("ListaReputacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  SELECT DISTINCT Imagens.Imagem Imagem
        ///               , Profissional.CodigoProfissional CodigoProfissional
        ///               , (Pessoa.PrimeiroNomePessoa || &apos; &apos; || Pessoa.SobreNomePessoa) NomeProfissional 
        ///               , (ClasseProfissional.ConselhoProfissional || &apos; &apos; || CAST(RelacaoProfissionalClasse.NumeroRegistroProfissional AS VARCHAR) || &apos;-&apos; ||  Estado.AbreviacaoEstado) RegistroProfissional 
        ///               , EspecialidadeProfissional.DescricaoEspecialidadeProfissional EspecialidadeProfissional 
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListarProfissionais {
            get {
                return ResourceManager.GetString("ListarProfissionais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  SELECT DISTINCT Imagens.Imagem Imagem
        ///               , Profissional.CodigoProfissional CodigoProfissional
        ///               , (Pessoa.PrimeiroNomePessoa || &apos; &apos; || Pessoa.SobreNomePessoa) NomeProfissional 
        ///               , (ClasseProfissional.ConselhoProfissional || &apos; &apos; || CAST(RelacaoProfissionalClasse.NumeroRegistroProfissional AS VARCHAR) || &apos;-&apos; ||  Estado.AbreviacaoEstado) RegistroProfissional 
        ///               , EspecialidadeProfissional.DescricaoEspecialidadeProfissional EspecialidadeProfissional 
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListarTodosProfissionais {
            get {
                return ResourceManager.GetString("ListarTodosProfissionais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       SELECT *
        ///        FROM Consulta
        ///  INNER JOIN Tratamento
        ///          ON Consulta.CodigoConsulta = Tratamento.CodigoConsulta
        ///       WHERE 1 = 1
        ///         AND Consulta.CodigoPaciente = @CodigoPaciente
        ///         AND Tratamento.TratamentoAtivado = 1;.
        /// </summary>
        internal static string ListaTratamentosAviso {
            get {
                return ResourceManager.GetString("ListaTratamentosAviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       SELECT DISTINCT COUNT(Consulta.CodigoPaciente) PacientesAtendidos
        ///        FROM Consulta
        ///       WHERE 1 = 1        
        ///         AND Consulta.CodigoProfissional = @CodigoProfissional
        ///         AND Consulta.SituacaoConsulta = 4 /* 4. Consulta Realizada */.
        /// </summary>
        internal static string PacientesAtendidos {
            get {
                return ResourceManager.GetString("PacientesAtendidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  INSERT INTO DadosAdicionais
        ///           ( CodigoPessoa
        ///           , DDDTelefoneDadosAdicionais
        ///           , NumeroTelefoneDadosAdicionais
        ///           , DDDCelularDadosAdicionais
        ///           , NumeroCelularDadosAdicionais
        ///           , EmailDadosAdicionais )
        ///      VALUES
        ///           ( (SELECT CodigoPessoa FROM Pessoa WHERE CPFPessoa = @CPFPessoa)
        ///           , @DDDTelefoneDadosAdicionais
        ///           , @NumeroTelefoneDadosAdicionais
        ///           , @DDDCelularDadosAdicionais
        ///           , @NumeroCelularDado [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProfissionalInsertDados {
            get {
                return ResourceManager.GetString("ProfissionalInsertDados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  INSERT INTO Endereco
        ///           ( CodigoPessoa
        ///           , LogradouroEndereco
        ///           , NumeroEndereco
        ///           , ComplementoEndereco
        ///           , BairroEndereco
        ///           , CodigoMunicipio
        ///           , CodigoEstado
        ///           , CepEndereco
        ///           , TipoEndereco )
        ///      VALUES
        ///           ( (SELECT CodigoPessoa FROM Pessoa WHERE CPFPessoa = @CPFPessoa)
        ///           , @LogradouroEndereco
        ///           , @NumeroEndereco
        ///           , @ComplementoEndereco
        ///           , @BairroEndereco
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProfissionalInsertEndereco {
            get {
                return ResourceManager.GetString("ProfissionalInsertEndereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    INSERT INTO Paciente
        ///             ( CodigoUsuario )
        ///        VALUES
        ///             ( (SELECT CodigoUsuario FROM Usuario WHERE LoginUsuario = @LoginUsuario ) ).
        /// </summary>
        internal static string ProfissionalInsertPaciente {
            get {
                return ResourceManager.GetString("ProfissionalInsertPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    INSERT INTO Pessoa
        ///             ( PrimeiroNomePessoa
        ///             , SobreNomePessoa
        ///             , CPFPessoa
        ///             , DataNascimentoPessoa )
        ///        VALUES
        ///             ( @PrimeiroNomePessoa
        ///             , @SobreNomePessoa
        ///             , @CPFPessoa
        ///             , @DataNascimentoPessoa ).
        /// </summary>
        internal static string ProfissionalInsertPessoa {
            get {
                return ResourceManager.GetString("ProfissionalInsertPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    INSERT INTO Profissional
        ///             ( CodigoUsuario )
        ///        VALUES
        ///             ( (SELECT CodigoUsuario FROM Usuario WHERE LoginUsuario = @LoginUsuario ) ).
        /// </summary>
        internal static string ProfissionalInsertProfissional {
            get {
                return ResourceManager.GetString("ProfissionalInsertProfissional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    INSERT INTO RelacaoProfissionalClasse
        ///             ( CodigoProfissional
        ///             , CodigoClasseProfissional
        ///             , NumeroRegistroProfissional )
        ///        VALUES
        ///             ( (SELECT CodigoProfissional
        ///                  FROM Profissional
        ///                  JOIN Usuario
        ///                    ON Usuario.CodigoUsuario = Profissional.CodigoUsuario
        ///                 WHERE 1 = 1
        ///                   AND Usuario.LoginUsuario = @LoginUsuario )
        ///             , (SELECT CodigoClasseProfissional FROM  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProfissionalInsertRelacao {
            get {
                return ResourceManager.GetString("ProfissionalInsertRelacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    INSERT INTO Usuario
        ///             ( CodigoPessoa
        ///             , LoginUsuario
        ///             , SenhaUsuario
        ///             , TipoUsuario )
        ///        VALUES
        ///             ( (SELECT CodigoPessoa FROM Pessoa WHERE CPFPessoa = @CPFPessoa)
        ///             , @LoginUsuario
        ///             , @SenhaUsuario
        ///             , @TipoUsuario ).
        /// </summary>
        internal static string ProfissionalInsertUsuario {
            get {
                return ResourceManager.GetString("ProfissionalInsertUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CodigoConsulta 
        ///  FROM Consulta 
        /// WHERE 1 = 1
        ///   AND CodigoProfissional = @CodigoProfissional
        ///   AND CodigoPaciente = @CodigoPaciente
        ///   AND SituacaoConsulta = @SituacaoConsulta
        ///   AND TipoPagamentoConsulta = @TipoPagamentoConsulta
        ///   AND DataRealizacaoConsulta = @DataRealizacaoConsulta
        ///   AND HoraInicialConsulta  = @HoraInicialConsulta 
        ///   AND MinutoInicialConsulta = @MinutoInicialConsulta
        ///   AND HoraFinalConsulta = @HoraFinalConsulta
        ///   AND MinutoFinalConsulta = @MinutoFinalConsulta.
        /// </summary>
        internal static string RecuperarCodigoConsulta {
            get {
                return ResourceManager.GetString("RecuperarCodigoConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       SELECT Pessoa.PrimeiroNomePessoa || &apos; &apos; || Pessoa.SobreNomePessoa
        ///           , Consulta.CodigoConsulta
        ///           , Consulta.DataRealizacaoConsulta DataConsulta
        ///           , Consulta.HoraInicialConsulta HoraInicio
        ///           , Consulta.MinutoInicialConsulta MinutoInicio
        ///        FROM Consulta
        ///  INNER JOIN Profissional ON Consulta.CodigoProfissional = Profissional.CodigoProfissional
        ///  INNER JOIN Usuario ON Profissional.CodigoUsuario = Usuario.CodigoUsuario
        ///  INNER JOIN Pessoa ON Usuario.CodigoPe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecuperarConsultaServicoEmail {
            get {
                return ResourceManager.GetString("RecuperarConsultaServicoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      SELECT *
        ///       FROM DadosAdicionais
        /// INNER JOIN Pessoa
        ///         ON DadosAdicionais.CodigoPessoa = Pessoa.CodigoPessoa
        /// INNER JOIN Usuario
        ///         ON Pessoa.CodigoPessoa = Usuario.CodigoPessoa
        /// INNER JOIN Paciente
        ///         ON Usuario.CodigoUsuario = Paciente.CodigoUsuario
        ///      WHERE 1 = 1
        ///        AND Paciente.CodigoPaciente = @CodigoPaciente.
        /// </summary>
        internal static string RecuperarContatoPaciente {
            get {
                return ResourceManager.GetString("RecuperarContatoPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///  FROM ConfiguracaoHorario 
        /// WHERE 1 = 1
        ///   AND CodigoProfissional = @CodigoProfissional
        ///   AND CodigoDiaConsulta = @CodigoDiaConsulta.
        /// </summary>
        internal static string RecuperarDadosConfiguracaoHorario {
            get {
                return ResourceManager.GetString("RecuperarDadosConfiguracaoHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * 
        ///  FROM ConfiguracaoConsulta 
        /// WHERE 1 = 1
        ///   AND CodigoProfissional = @CodigoProfissional.
        /// </summary>
        internal static string RecuperarDadosConsulta {
            get {
                return ResourceManager.GetString("RecuperarDadosConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      SELECT Pessoa.PrimeiroNomePessoa || &apos; &apos; || Pessoa.SobreNomePessoa NomePaciente
        ///       FROM Pessoa
        /// INNER JOIN Usuario
        ///         ON Pessoa.CodigoPessoa = Usuario.CodigoPessoa
        /// INNER JOIN Paciente
        ///         ON Usuario.CodigoUsuario = Paciente.CodigoUsuario
        ///      WHERE 1 = 1
        ///        AND Paciente.CodigoPaciente = @CodigoPaciente.
        /// </summary>
        internal static string RecuperarNomePaciente {
            get {
                return ResourceManager.GetString("RecuperarNomePaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      SELECT Pessoa.PrimeiroNomePessoa || &apos; &apos; || Pessoa.SobreNomePessoa NomeProfissional
        ///       FROM Pessoa
        /// INNER JOIN Usuario
        ///         ON Pessoa.CodigoPessoa = Usuario.CodigoPessoa
        /// INNER JOIN Profissional
        ///         ON Usuario.CodigoUsuario = Profissional.CodigoUsuario
        ///      WHERE 1 = 1
        ///        AND Profissional.CodigoProfissional = @CodigoProfissional.
        /// </summary>
        internal static string RecuperarNomeProfissional {
            get {
                return ResourceManager.GetString("RecuperarNomeProfissional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        SELECT CodigoPessoa
        ///            , PrimeiroNomePessoa
        ///            , SobreNomePessoa
        ///            , CPFPessoa
        ///            , DataNascimentoPessoa
        ///         FROM Pessoa
        ///        WHERE 1 = 1 
        ///          AND CodigoPessoa = @CodigoPessoa.
        /// </summary>
        internal static string RecuperarPessoaLogin {
            get {
                return ResourceManager.GetString("RecuperarPessoaLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COALESCE(PrecoConsultaProfissional, 0) PrecoConsultaProfissional
        ///  FROM ConfiguracaoConsulta
        /// WHERE 1 = 1
        ///   AND CodigoProfissional = @CodigoProfissional
        ///.
        /// </summary>
        internal static string RecuperarPrecoConsulta {
            get {
                return ResourceManager.GetString("RecuperarPrecoConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        SELECT CodigoUsuario
        ///            , CodigoPessoa
        ///            , LoginUsuario
        ///            , SenhaUsuario
        ///            , TipoUsuario
        ///         FROM Usuario
        ///        WHERE 1 = 1 
        ///          AND LoginUsuario = @LoginUsuario 
        ///          AND SenhaUsuario = @SenhaUsuario.
        /// </summary>
        internal static string RecuperarUsuarioLogin {
            get {
                return ResourceManager.GetString("RecuperarUsuarioLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  INSERT INTO Avaliacao
        ///           ( CodigoConsulta
        ///           , SituacaoAvaliacao
        ///           , NotaAvaliacao
        ///           , DescricaoAvaliacao )
        ///    VALUES ( @CodigoConsulta
        ///           , @SituacaoAvaliacao
        ///           , @NotaAvaliacao
        ///           , @DescricaoAvaliacao ).
        /// </summary>
        internal static string SalvarAvaliacao {
            get {
                return ResourceManager.GetString("SalvarAvaliacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///  FROM ConfiguracaoHorario
        /// WHERE 1 = 1
        ///   AND CodigoProfissional = @CodigoProfissional.
        /// </summary>
        internal static string SelecionarConfiguracaoHorario {
            get {
                return ResourceManager.GetString("SelecionarConfiguracaoHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///  FROM Consulta
        /// WHERE 1 = 1
        ///   AND CodigoProfissional = @CodigoProfissional
        ///   AND DataRealizacaoConsulta = @DataRealizacaoConsulta   
        ///   AND SituacaoConsulta NOT IN (3,5) /* Código 3 =&gt; Consulta Cancelada, Código 5 =&gt; Consulta Indeferida */.
        /// </summary>
        internal static string SelecionarConsultas {
            get {
                return ResourceManager.GetString("SelecionarConsultas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///  FROM Consulta
        /// WHERE 1 = 1
        ///   AND CodigoProfissional = @CodigoProfissional
        ///   AND DataRealizacaoConsulta = @DataRealizacaoConsulta
        ///   AND CodigoPaciente = @CodigoPaciente
        ///   AND SituacaoConsulta NOT IN (3,5) /* Código 3 =&gt; Consulta Cancelada, Código 5 =&gt; Consulta Indeferida */
        ///
        ///UNION ALL
        ///
        ///SELECT *
        ///  FROM Consulta
        /// WHERE 1 = 1
        ///   AND CodigoProfissional = @CodigoProfissional
        ///   AND DataRealizacaoConsulta = @DataRealizacaoConsulta
        ///   AND CodigoPaciente &lt;&gt; @CodigoPaciente
        ///   AND Situa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelecionarConsultasPaciente {
            get {
                return ResourceManager.GetString("SelecionarConsultasPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     SELECT CheckEmail.CodigoCheckEMail
        ///         , CheckEmail.CodigoConsulta 
        ///      FROM CheckEmail
        ///INNER JOIN Consulta
        ///        ON CheckEmail.CodigoConsulta = Consulta.CodigoConsulta
        ///     WHERE 1 = 1
        ///       AND CAST(Consulta.DataRealizacaoConsulta AS DATETIME) &gt; CAST(DATETIME(&apos;NOW&apos;) AS DATETIME)
        ///       AND Consulta.CodigoPaciente = @CodigoPaciente
        ///.
        /// </summary>
        internal static string SelectCheckEmail {
            get {
                return ResourceManager.GetString("SelectCheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      UPDATE Tratamento      
        ///        SET CodigoConsulta = @CodigoConsulta
        ///          , NomeTratamento = @NomeTratamento
        ///          , DescricaoTratamento = @DescricaoTratamento
        ///          , InicioTratamento = @InicioTratamento
        ///          , TerminoTratamento = @TerminoTratamento
        ///          , HoraInicio = @HoraInicio
        ///          , MinutoInicio = @MinutoInicio
        ///          , FrequenciaDias = @FrequenciaDias
        ///          , FrequenciaHoras = @FrequenciaHoras
        ///          , TratamentoAtivado = @TratamentoAtivado
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateTratamento {
            get {
                return ResourceManager.GetString("UpdateTratamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    INSERT INTO DadosAdicionais 
        ///        ( CodigoPessoa 
        ///        , DDDTelefoneDadosAdicionais 
        ///        , NumeroTelefoneDadosAdicionais
        ///        , DDDCelularDadosAdicionais
        ///        , NumeroCelularDadosAdicionais
        ///        , EmailDadosAdicionais ) 
        ///   VALUES 
        ///        ( (SELECT CodigoPessoa FROM Pessoa WHERE CPFPessoa = @CPFPessoa) 
        ///        , @DDDTelefoneDadosAdicionais 
        ///        , @NumeroTelefoneDadosAdicionais
        ///        , @DDDCelularDadosAdicionais
        ///        , @NumeroCelularDadosAdicionais
        ///        , @Ema [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UsuarioInsertDados {
            get {
                return ResourceManager.GetString("UsuarioInsertDados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    INSERT INTO Paciente 
        ///        ( CodigoUsuario ) 
        ///   VALUES 
        ///        ( (SELECT CodigoUsuario FROM Usuario WHERE LoginUsuario = @LoginUsuario ) ).
        /// </summary>
        internal static string UsuarioInsertPaciente {
            get {
                return ResourceManager.GetString("UsuarioInsertPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    INSERT INTO Pessoa 
        ///        ( PrimeiroNomePessoa 
        ///        , SobreNomePessoa 
        ///        , CPFPessoa 
        ///        , DataNascimentoPessoa ) 
        ///   VALUES 
        ///        ( @PrimeiroNomePessoa 
        ///        , @SobreNomePessoa
        ///        , @CPFPessoa
        ///        , @DataNascimentoPessoa ).
        /// </summary>
        internal static string UsuarioInsertPessoa {
            get {
                return ResourceManager.GetString("UsuarioInsertPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    INSERT INTO Usuario 
        ///        ( CodigoPessoa 
        ///        , LoginUsuario 
        ///        , SenhaUsuario 
        ///        , TipoUsuario ) 
        ///   VALUES 
        ///        ( (SELECT CodigoPessoa FROM Pessoa WHERE CPFPessoa = @CPFPessoa) 
        ///        , @LoginUsuario
        ///        , @SenhaUsuario
        ///        , 1 ).
        /// </summary>
        internal static string UsuarioInsertUsuario {
            get {
                return ResourceManager.GetString("UsuarioInsertUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///  FROM Consulta
        /// WHERE 1 = 1
        ///   AND CodigoProfissional = @CodigoProfissional
        ///   AND DataRealizacaoConsulta = @DataRealizacaoConsulta
        ///   AND HoraInicialConsulta = @HoraInicialConsulta
        ///   AND MinutoInicialConsulta = @MinutoInicialConsulta
        ///   AND HoraFinalConsulta = @HoraFinalConsulta
        ///   AND MinutoFinalConsulta = @MinutoFinalConsulta
        ///   AND SituacaoConsulta NOT IN (3,5) /* Código 3 =&gt; Consulta Cancelada, Código 5 =&gt; Consulta Indeferida */.
        /// </summary>
        internal static string VerificarExistenciaConsulta {
            get {
                return ResourceManager.GetString("VerificarExistenciaConsulta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  SELECT COUNT(*) QuantidadeLinhas 
        ///   FROM Usuario 
        ///  WHERE 1 = 1 
        ///    AND LoginUsuario = @LoginUsuario
        ///    AND SenhaUsuario = @SenhaUsuario.
        /// </summary>
        internal static string VerificarUsuario {
            get {
                return ResourceManager.GetString("VerificarUsuario", resourceCulture);
            }
        }
    }
}
