//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SensorGasAPI.Repositorio.Resources.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SensorGasAPI.Repositorio.Resources.Scripts.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to        SELECT Consulta.CodigoConsulta CodigoConsulta
        ///           ,  Consulta.DataRealizacaoConsulta
        ///           , (Pessoa.PrimeiroNomePessoa || &apos; &apos; || Pessoa.SobreNomePessoa) NomeProfissional
        ///           ,  Avaliacao.CodigoAvaliacao CodigoAvaliacao
        ///           ,  Avaliacao.SituacaoAvaliacao
        ///           ,  Avaliacao.NotaAvaliacao
        ///           ,  Avaliacao.DescricaoAvaliacao
        ///         FROM Consulta
        ///   INNER JOIN Profissional ON Consulta.CodigoProfissional = Profissional.CodigoProfissional
        ///   INNER JOIN Usuar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DetalheAvaliacaoPaciente {
            get {
                return ResourceManager.GetString("DetalheAvaliacaoPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      SELECT  Imagens.Imagem Imagem
        ///           , (Pessoa.PrimeiroNomePessoa || &apos; &apos; || Pessoa.SobreNomePessoa) NomeProfissional
        ///           , Consulta.CodigoConsulta CodigoConsulta
        ///           , Consulta.DataRealizacaoConsulta
        ///        FROM Consulta
        ///  INNER JOIN Profissional ON Consulta.CodigoProfissional = Profissional.CodigoProfissional
        ///  INNER JOIN Usuario ON Profissional.CodigoUsuario = Usuario.CodigoUsuario
        ///  INNER JOIN Pessoa ON Usuario.CodigoPessoa = Pessoa.CodigoPessoa
        ///   LEFT JOIN Imagens ON Usu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListaAvaliacoesPaciente {
            get {
                return ResourceManager.GetString("ListaAvaliacoesPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  INSERT INTO Avaliacao
        ///           ( CodigoConsulta
        ///           , SituacaoAvaliacao
        ///           , NotaAvaliacao
        ///           , DescricaoAvaliacao )
        ///    VALUES ( @CodigoConsulta
        ///           , @SituacaoAvaliacao
        ///           , @NotaAvaliacao
        ///           , @DescricaoAvaliacao ).
        /// </summary>
        internal static string SalvarAvaliacao {
            get {
                return ResourceManager.GetString("SalvarAvaliacao", resourceCulture);
            }
        }
    }
}
